    development:
        adapter: mysql
        database: 'game_finder2'
        username: gamefinder
        password: police73
        socket: /private/tmp/mysql.sock
    test:
        adapter: mysql
        database: game_finder
        username: root
        password:
        host: localhost
    production:
        adapter: mysql
        database: 'game_finder2'
        username: gamefinder
        password: police73
        host: localhost